/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ai.slopshield

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appCanBeCreated() {
        val classUnderTest = App()
        assertNotNull(classUnderTest, "app should be creatable")
    }
}
