package ai.slopshield.core

import io.github.oshai.kotlinlogging.KotlinLogging
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.asCoroutineDispatcher
import kotlinx.coroutines.async
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withContext
import java.util.concurrent.Executors
import java.util.concurrent.TimeUnit

private val logger = KotlinLogging.logger {}

/**
 * Result of an AI processing task.
 * 
 * @property stdout The standard output generated by the AI process.
 * @property stderr The standard error generated by the AI process.
 * @property exitCode The exit code returned by the AI process.
 */
data class AiResult(
    val stdout: String,
    val stderr: String,
    val exitCode: Int
)

/**
 * Generic AI execution engine - a shared wrapper for the Gemini CLI.
 *
 * It manages a fixed thread pool to throttle AI processing throughput,
 * ensuring that multiple domain services don't overwhelm the system with 
 * parallel AI calls.
 *
 * @property maxParallelTasks The maximum number of concurrent Gemini CLI processes allowed.
 * Defaults to the 'slopshield.ai.parallelism' system property or 3.
 */
open class GeminiCliAiService(
    maxParallelTasks: Int = System.getProperty("slopshield.ai.parallelism", "3").toInt()
) : AiService {

    private val executor = Executors.newFixedThreadPool(maxParallelTasks)
    private val dispatcher: CoroutineDispatcher = executor.asCoroutineDispatcher()

    /**
     * Processes the given prompt and context content using the Gemini CLI.
     *
     * @param prompt The prompt to pass as the first argument to gemini.
     * @param context The supporting content or data for the AI model to process.
     * @param timeoutSeconds How long to wait for the process to complete.
     * @return The result of the AI processing containing stdout, stderr, and exit code.
     */
    override suspend fun process(
        prompt: String,
        context: String,
        timeoutSeconds: Long
    ): AiResult = withContext(dispatcher) {
        // Use runBlocking to hold the thread pool thread and prevent yielding 
        // during suspension points, ensuring the pool size limits the number 
        // of concurrent OS processes.
        runBlocking {
            val process = ProcessBuilder("gemini", prompt, "-e", "")
                .redirectErrorStream(false)
                .start()

            coroutineScope {
                // Start reading stdout and stderr concurrently to prevent deadlock
                val stdoutDeferred = async(Dispatchers.IO) {
                    process.inputStream.bufferedReader().use { it.readText() }.trim()
                }
                val stderrDeferred = async(Dispatchers.IO) {
                    process.errorStream.bufferedReader().use { it.readText() }.trim()
                }

                // Write context to process stdin
                launch(Dispatchers.IO) {
                    try {
                        process.outputStream.bufferedWriter().use { it.write(context) }
                    } catch (e: Exception) {
                        logger.warn { "AIService: Failed to write to process stdin: ${e.message}" }
                    }
                }

                try {
                    val finished = withContext(Dispatchers.IO) {
                        process.waitFor(timeoutSeconds, TimeUnit.SECONDS)
                    }

                    val stdout = stdoutDeferred.await()
                    val stderr = stderrDeferred.await()

                    if (!finished) {
                        logger.error { "AIService: Gemini process timed out for prompt: ${prompt.take(50)}..." }
                        process.destroyForcibly()
                        AiResult(stdout, stderr, -1)
                    } else {
                        AiResult(stdout, stderr, process.exitValue())
                    }
                } catch (e: Exception) {
                    logger.error(e) { "AIService: Exception during Gemini execution" }
                    process.destroyForcibly()
                    AiResult("", e.message ?: "Unknown error", -1)
                } finally {
                    process.inputStream.close()
                    process.errorStream.close()
                    process.outputStream.close()
                }
            }
        }
    }

    /**
     * Gracefully shuts down the thread pool, ensuring all resources are released.
     */
    override fun shutdown() {
        executor.shutdown()
        if (!executor.awaitTermination(5, TimeUnit.SECONDS)) {
            executor.shutdownNow()
        }
    }
}
